### ISSUE TITLE
Cannot run on Ubuntu 16.04

### ISSUE THREAD

**Issue by dlenskyi** [converge/instapy-dashboard#16]
> instapy-dashboard@0.3.0 start /home/dlenskyi/Desktop/instapy-dashboard
> concurrently --kill-others-on-fail "react-scripts start" "npm run server"

[1] 
[1] > instapy-dashboard@0.3.0 server /home/dlenskyi/Desktop/instapy-dashboard
[1] > node ./src/services/server.js
[1] 
[1] fs.js:119
[1]     throw err;
[1]     ^
[1] 
[1] Error: ENOENT: no such file or directory, scandir '/Users/dlenskyi/InstaPy/logs'
[1]     at Object.readdirSync (fs.js:806:3)
[1]     at Object.getLogsFolder (/home/dlenskyi/Desktop/instapy-dashboard/src/services/utils.js:9:24)
[1]     at Object.<anonymous> (/home/dlenskyi/Desktop/instapy-dashboard/src/services/server.js:21:26)
[1]     at Module._compile (internal/modules/cjs/loader.js:738:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
[1]     at Module.load (internal/modules/cjs/loader.js:630:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:562:3)
[1]     at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
[1]     at internal/main/run_main_module.js:21:11
[1] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[1] npm ERR! instapy-dashboard@0.3.0 server: `node ./src/services/server.js`
[1] npm ERR! Exit status 1
npm ERR! 
[1] npm ERR! Failed at the instapy-dashboard@0.3.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1] 
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/dlenskyi/.npm/_logs/2019-03-07T08_30_12_676Z-debug.log
[1] npm run server exited with code 1
--> Sending SIGTERM to other processes..
[0] react-scripts start exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! instapy-dashboard@0.3.0 start: `concurrently --kill-others-on-fail "react-scripts start" "npm run server"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the instapy-dashboard@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dlenskyi/.npm/_logs/2019-03-07T08_30_12_795Z-debug.log

tried #10 solution but still the same error.
require('better-sqlite3') shows as follow:
 { [Function: Database]
  Integer:
   { [Function: Integer]
     fromString: [Function: fromString],
     fromNumber: [Function: fromNumber],
     fromBits: [Function: fromBits],
     isInstance: [Function: isInstance],
     MAX_VALUE: Integer { high: 2147483647, low: -1 },
     MIN_VALUE: Integer { high: -2147483648, low: 0 },
     ZERO: Integer { high: 0, low: 0 },
     ONE: Integer { high: 0, low: 1 },
     NEG_ONE: Integer { high: -1, low: -1 } },
  SqliteError: [Function: SqliteError] }
when running npm install shows:
npm WARN ts-pnp@1.0.1 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 39557 packages in 11.865s
found 63 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
when tried to 'npm audit fix' those errors didn't fix
Please help

**Comment by converge** [comment]
Hey @dlenskyi , on Ubuntu the home folder is:
```'/home/dlenskyi/InstaPy/logs'```
you're using MacOS style: ```'/Users/dlenskyi/InstaPy/logs'```

**Comment by dlenskyi** [comment]
oh, thanks so much @converge , I will try this in a while :D
