### ISSUE TITLE
Error running on Ubuntu

### ISSUE THREAD

**Issue by Javi4** [converge/instapy-dashboard#21]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.7.0
3 info using node@v11.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle instapy-dashboard@0.3.0~prestart: instapy-dashboard@0.3.0
6 info lifecycle instapy-dashboard@0.3.0~start: instapy-dashboard@0.3.0
7 verbose lifecycle instapy-dashboard@0.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle instapy-dashboard@0.3.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/instapy-dashboard/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle instapy-dashboard@0.3.0~start: CWD: /root/instapy-dashboard
10 silly lifecycle instapy-dashboard@0.3.0~start: Args: [ '-c',
10 silly lifecycle   'concurrently --kill-others-on-fail "react-scripts start" "npm run server"' ]
11 info lifecycle instapy-dashboard@0.3.0~start: Failed to exec start script
12 verbose stack Error: instapy-dashboard@0.3.0 start: `concurrently --kill-others-on-fail "react-scripts start" "npm run server"`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:193:13)
12 verbose stack     at maybeClose (internal/child_process.js:1001:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
13 verbose pkgid instapy-dashboard@0.3.0
14 verbose cwd /root/instapy-dashboard
15 verbose Linux 4.15.0-47-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v11.13.0
18 verbose npm  v6.7.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error instapy-dashboard@0.3.0 start: `concurrently --kill-others-on-fail "react-scripts start" "npm run server"`
23 error spawn ENOENT
24 error Failed at the instapy-dashboard@0.3.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by converge** [comment]
do you have the .env file on the root folder?

**Comment by EmilyLuna** [comment]
Where can i found that .env ?? is not apearing on my /instapy-dashboard folder

**Comment by converge** [comment]
@EmilyLuna have a look: https://github.com/converge/instapy-dashboard#project-setup
