### ISSUE TITLE
Error: The package "react-emotion" has been replaced by "@emotion/styled" in version 10. 

### ISSUE THREAD

**Issue by andreescocard** [converge/instapy-dashboard#5]
Full error: Error: The package "react-emotion" has been replaced by "@emotion/styled" in version 10. See https://emotion.sh/docs/migrating-to-emotion-10 for more information on migrating.

Tried installing @emotion/styled, don't work, trying to follow the incremental migration provided on link, any news i post here

**Comment by andreescocard** [comment]
Tried cloning the project again, now i am getting:
 Cannot find module '../build/better_sqlite3.node'

**Comment by andreescocard** [comment]
` Error: Cannot find module '../build/better_sqlite3.node'
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
[1]     at Module.require (internal/modules/cjs/loader.js:636:17)
[1]     at require (internal/modules/cjs/helpers.js:20:18)
[1]     at Object.<anonymous> (/home/pi/instapy-dashboard/node_modules/better-sqlite3/lib/database.js:5:21)
[1]     at Module._compile (internal/modules/cjs/loader.js:688:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
[1]     at Module.load (internal/modules/cjs/loader.js:598:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! instapy-dashboard@0.2.2 server: `node ./src/services/server.js`
`

**Comment by andreescocard** [comment]
https://github.com/JoshuaWise/better-sqlite3/issues/214
