### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HCWcoder** [converge/instapy-dashboard#8]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle instapy-dashboard@0.2.2~prestart: instapy-dashboard@0.2.2
6 info lifecycle instapy-dashboard@0.2.2~start: instapy-dashboard@0.2.2
7 verbose lifecycle instapy-dashboard@0.2.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle instapy-dashboard@0.2.2~start: PATH: C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\user\Documents\GitHub\instapy-dashboard\node_modules\.bin;C:\Users\user\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Python35\Lib\site-packages\PyQt5;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\xampp\php;C:\Python35\Lib\site-packages\PyQt5;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Users\user\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python37-32\;C:\Users\user\AppData\Local\Programs\Python\Python36-32\Scripts\pyuic5.exe;C:\Users\user\AppData\Local\Programs\Python;C:\Users\user\AppData\Local\Programs\Python\Python36;c:\users\user\appdata\local\programs\python\python36\lib\site-packages\pip.exe;C:\Users\user\AppData\Local\Programs\Python\Python36-32\Scripts;C:\Users\user\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\user\Desktop\cyka.iopython;c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages (3.12.0);C:\Users\user\Downloads\InstaPy-master;C:\Users\user\Desktop\cyka.iopython\randomscustom.py;C:\Users\user\Downloads\php-7.2.7-nts-Win32-VC15-x64;C:\Users\user\Desktop\cyka.iopython\igflash.py;C:\Users\user\AppData\Local\atom\bin;c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages;c:\users\user\appdata\local\programs\python\python36-;C:\Users\user\AppData\Roaming\npm;C:\Users\user\AppData\Local\Programs\Python\Python37-32\;C:\xampp\php\;
9 verbose lifecycle instapy-dashboard@0.2.2~start: CWD: C:\Users\user\Documents\GitHub\instapy-dashboard
10 silly lifecycle instapy-dashboard@0.2.2~start: Args: [ '/d /s /c',
10 silly lifecycle   'concurrently --kill-others-on-fail "react-scripts start" "npm run server"' ]
11 silly lifecycle instapy-dashboard@0.2.2~start: Returned: code: 1  signal: null
12 info lifecycle instapy-dashboard@0.2.2~start: Failed to exec start script
13 verbose stack Error: instapy-dashboard@0.2.2 start: `concurrently --kill-others-on-fail "react-scripts start" "npm run server"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid instapy-dashboard@0.2.2
15 verbose cwd C:\Users\user\Documents\GitHub\instapy-dashboard
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.14.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error instapy-dashboard@0.2.2 start: `concurrently --kill-others-on-fail "react-scripts start" "npm run server"`
22 error Exit status 1
23 error Failed at the instapy-dashboard@0.2.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by tiranin** [comment]
**I think I have something similar happening:**
E:\Users\lsouz\Documents\GitHub\instapy-dashboard\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
 )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\lsouz\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1

gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Users\lsouz\Documents\GitHub\instapy-dashboard\node_modules\integer
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lsouz\AppData\Roaming\npm-cache\_logs\2018-12-23T10_38_21_390Z-debug.log

**Comment by schonert** [comment]
@tiranin not sure the issues are related. I faced the same `node-gyp` error. This solved it for me. https://github.com/nodejs/node-gyp/issues/569#issuecomment-445802313

@HCWcoder sorry i'm of no help to the original issue

**Comment by HCWcoder** [comment]
> @tiranin not sure the issues are related. I faced the same `node-gyp` error. This solved it for me. [nodejs/node-gyp#569 (comment)](https://github.com/nodejs/node-gyp/issues/569#issuecomment-445802313)
> 
> @HCWcoder sorry i'm of no help to the original issue

@schonert 
what do you mean brother ? please help

**Comment by HCWcoder** [comment]
I still  getting this error i couldnt use this thing ever please i need help  @converge 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle instapy-dashboard@0.2.2~prestart: instapy-dashboard@0.2.2
6 info lifecycle instapy-dashboard@0.2.2~start: instapy-dashboard@0.2.2
7 verbose lifecycle instapy-dashboard@0.2.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle instapy-dashboard@0.2.2~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\JayPixx\Documents\GitHub\instapy-dashboard\node_modules\.bin;C:\Python35\Lib\site-packages\PyQt5;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\xampp\php;C:\Program Files\nodejs\;C:\Python35\Lib\site-packages\PyQt5;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs\;C:\Users\JayPixx\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\JayPixx\AppData\Local\Programs\Python\Python37-32\;C:\Users\JayPixx\AppData\Local\Programs\Python\Python36-32\Scripts\pyuic5.exe;C:\Users\JayPixx\AppData\Local\Programs\Python;C:\Users\JayPixx\AppData\Local\Programs\Python\Python36;c:\users\jaypixx\appdata\local\programs\python\python36\lib\site-packages\pip.exe;C:\Users\JayPixx\AppData\Local\Programs\Python\Python36-32\Scripts;C:\Users\JayPixx\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\JayPixx\Desktop\cyka.iopython;c:\users\jaypixx\appdata\local\programs\python\python36-32\lib\site-packages (3.12.0);C:\Users\JayPixx\Downloads\InstaPy-master;C:\Users\JayPixx\Desktop\cyka.iopython\randomscustom.py;C:\Users\JayPixx\Downloads\php-7.2.7-nts-Win32-VC15-x64;C:\Users\JayPixx\Desktop\cyka.iopython\igflash.py;C:\Users\JayPixx\AppData\Local\atom\bin;c:\users\jaypixx\appdata\local\programs\python\python36-32\lib\site-packages;c:\users\jaypixx\appdata\local\programs\python\python36-;C:\Users\JayPixx\AppData\Local\Programs\Python\Python37-32\;C:\xampp\php\;C:\Users\JayPixx\AppData\Roaming\npm
9 verbose lifecycle instapy-dashboard@0.2.2~start: CWD: C:\Users\JayPixx\Documents\GitHub\instapy-dashboard
10 silly lifecycle instapy-dashboard@0.2.2~start: Args: [ '/d /s /c',
10 silly lifecycle   'concurrently --kill-others-on-fail "react-scripts start" "npm run server"' ]
11 silly lifecycle instapy-dashboard@0.2.2~start: Returned: code: 1  signal: null
12 info lifecycle instapy-dashboard@0.2.2~start: Failed to exec start script
13 verbose stack Error: instapy-dashboard@0.2.2 start: `concurrently --kill-others-on-fail "react-scripts start" "npm run server"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid instapy-dashboard@0.2.2
15 verbose cwd C:\Users\JayPixx\Documents\GitHub\instapy-dashboard
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v11.6.0
19 verbose npm  v6.5.0-next.0
20 error code ELIFECYCLE
21 error errno 1
22 error instapy-dashboard@0.2.2 start: `concurrently --kill-others-on-fail "react-scripts start" "npm run server"`
22 error Exit status 1
23 error Failed at the instapy-dashboard@0.2.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by converge** [comment]
@HCWcoder did you fix it?

**Comment by HCWcoder** [comment]
Yup i had to un install node and clean everything and start from fresh did fix the issue

It worked 👌

**Comment by converge** [comment]
I believe is something related to better-sqlite compilation, probably deleting node_modules and running ```npm install``` would fix it also.
